In [1]:
%pip install -q pgserver psycopg2-binary sqlalchemy pandas pyarrow ucimlrepo

import pandas as pd
import pgserver
from sqlalchemy import create_engine, text

pg = pgserver.get_server('/tmp/hw3_pg', cleanup_mode='stop')
engine = create_engine(
    pg.get_uri().replace('postgresql://', 'postgresql+psycopg2://', 1),
    future=True,
    # фіксуємо часовий пояс сесії, щоб вивід TIMESTAMPTZ не залежав від машини (Colab = UTC)
    connect_args={'options': '-c timezone=Asia/Seoul'},
)

with engine.connect() as conn:
    version = conn.execute(text('SELECT version()')).scalar_one()
    print(version)

pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 200)


def q(sql: str) -> pd.DataFrame:
    """Виконати DQL-запит і повернути результат як DataFrame."""
    return pd.read_sql(text(sql), engine)


def run(sql: str) -> None:
    """Виконати DDL/DML у транзакції."""
    with engine.begin() as conn:
        conn.execute(text(sql))

Note: you may need to restart the kernel to use updated packages.

PostgreSQL 16.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11), 64-bit

In [2]:
import io
import zipfile
from pathlib import Path
from urllib.request import urlretrieve

DATA_URL = 'https://archive.ics.uci.edu/static/public/560/seoul+bike+sharing+demand.zip'

DATA_DIR = Path('data')
RAW_DIR = DATA_DIR / 'raw'
RAW_DIR.mkdir(parents=True, exist_ok=True)
zip_path = RAW_DIR / 'seoul_bike_sharing_demand.zip'

if not zip_path.exists():
    urlretrieve(DATA_URL, zip_path)

with zipfile.ZipFile(zip_path) as zf:
    print('Файли в архіві:', zf.namelist())
    member = next(n for n in zf.namelist() if n.lower().endswith('.csv'))
    raw_bytes = zf.read(member)

try:
    raw_text = raw_bytes.decode('utf-8')
    encoding_used = 'utf-8'
except UnicodeDecodeError:
    raw_text = raw_bytes.decode('cp1252')
    encoding_used = 'cp1252'

raw_df = pd.read_csv(io.StringIO(raw_text), dtype=str, keep_default_na=False)
print('Кодування джерела:', encoding_used)
print('Розмір сирого файлу:', raw_df.shape)
raw_df.head()

Файли в архіві: ['SeoulBikeData.csv']
Кодування джерела: utf-8
Розмір сирого файлу: (8760, 14)

,Date,Rented Bike Count,Hour,Temperature(C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0,0,0,Winter,No Holiday,Yes
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0,0,0,Winter,No Holiday,Yes
2,01/12/2017,173,2,-6,39,1,2000,-17.7,0,0,0,Winter,No Holiday,Yes
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0,0,0,Winter,No Holiday,Yes
4,01/12/2017,78,4,-6,36,2.3,2000,-18.6,0,0,0,Winter,No Holiday,Yes

In [3]:
RAW_COLUMNS = [
    'date_raw', 'rented_bike_count_raw', 'hour_raw', 'temperature_c_raw',
    'humidity_pct_raw', 'wind_speed_ms_raw', 'visibility_10m_raw',
    'dew_point_c_raw', 'solar_radiation_mj_raw', 'rainfall_mm_raw',
    'snowfall_cm_raw', 'seasons_raw', 'holiday_raw', 'functioning_day_raw',
]
assert raw_df.shape[1] == len(RAW_COLUMNS), raw_df.columns.tolist()

display(pd.DataFrame({'source_column': raw_df.columns, 'staging_column': RAW_COLUMNS}))

controlled_df = raw_df.copy()
controlled_df.columns = RAW_COLUMNS

csv_path = DATA_DIR / 'hw3_seoul_bike.csv'
controlled_df.to_csv(csv_path, index=False, encoding='utf-8')
print(csv_path, controlled_df.shape)

               source_column          staging_column
0                       Date                date_raw
1          Rented Bike Count   rented_bike_count_raw
2                       Hour                hour_raw
3             Temperature(C)       temperature_c_raw
4                Humidity(%)        humidity_pct_raw
5           Wind speed (m/s)       wind_speed_ms_raw
6           Visibility (10m)      visibility_10m_raw
7   Dew point temperature(C)         dew_point_c_raw
8    Solar Radiation (MJ/m2)  solar_radiation_mj_raw
9               Rainfall(mm)         rainfall_mm_raw
10             Snowfall (cm)         snowfall_cm_raw
11                   Seasons             seasons_raw
12                   Holiday             holiday_raw
13           Functioning Day     functioning_day_raw

data/hw3_seoul_bike.csv (8760, 14)

In [4]:
run("""
DROP TABLE IF EXISTS hw3_bike_rentals CASCADE;
DROP TABLE IF EXISTS hw3_bike_staging CASCADE;

CREATE TABLE hw3_bike_staging (
    date_raw               TEXT,
    rented_bike_count_raw  TEXT,
    hour_raw               TEXT,
    temperature_c_raw      TEXT,
    humidity_pct_raw       TEXT,
    wind_speed_ms_raw      TEXT,
    visibility_10m_raw     TEXT,
    dew_point_c_raw        TEXT,
    solar_radiation_mj_raw TEXT,
    rainfall_mm_raw        TEXT,
    snowfall_cm_raw        TEXT,
    seasons_raw            TEXT,
    holiday_raw            TEXT,
    functioning_day_raw    TEXT
);
""")

In [5]:
raw_conn = engine.raw_connection()

try:
    with raw_conn.cursor() as cur:
        with open(csv_path, 'r', encoding='utf-8', newline='') as file:
            cur.copy_expert(
                """
                COPY hw3_bike_staging (
                    date_raw, rented_bike_count_raw, hour_raw, temperature_c_raw,
                    humidity_pct_raw, wind_speed_ms_raw, visibility_10m_raw,
                    dew_point_c_raw, solar_radiation_mj_raw, rainfall_mm_raw,
                    snowfall_cm_raw, seasons_raw, holiday_raw, functioning_day_raw
                )
                FROM STDIN
                WITH (
                    FORMAT csv,
                    HEADER true,
                    DELIMITER ','
                )
                """,
                file,
            )
    raw_conn.commit()
finally:
    raw_conn.close()

q('SELECT COUNT(*) AS loaded_rows FROM hw3_bike_staging')

   loaded_rows
0         8760

**Висновок:** у staging завантажено **8 760** рядків — рівно стільки, скільки рядків даних у CSV (365 днів × 24 години), тобто `COPY` не втратив і не задублював жодного запису, а заголовок коректно пропущено (`HEADER true`).

In [6]:
q(r"""
SELECT * FROM hw3_bike_staging LIMIT 5;
""")

,date_raw,rented_bike_count_raw,hour_raw,temperature_c_raw,humidity_pct_raw,wind_speed_ms_raw,visibility_10m_raw,dew_point_c_raw,solar_radiation_mj_raw,rainfall_mm_raw,snowfall_cm_raw,seasons_raw,holiday_raw,functioning_day_raw
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0,0,0,Winter,No Holiday,Yes
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0,0,0,Winter,No Holiday,Yes
2,01/12/2017,173,2,-6,39,1,2000,-17.7,0,0,0,Winter,No Holiday,Yes
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0,0,0,Winter,No Holiday,Yes
4,01/12/2017,78,4,-6,36,2.3,2000,-18.6,0,0,0,Winter,No Holiday,Yes

In [7]:
run(r"""
CREATE OR REPLACE FUNCTION hw3_to_num(p TEXT)
RETURNS NUMERIC
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT CASE
               WHEN TRIM(p) ~ '^[-+]?([0-9]+([.][0-9]*)?|[.][0-9]+)$'
               THEN TRIM(p)::NUMERIC
           END
$$;

DROP TABLE IF EXISTS hw3_bike_rentals CASCADE;

CREATE TABLE hw3_bike_rentals (
    rental_id           BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    rental_date         DATE        NOT NULL,
    rental_hour         SMALLINT    NOT NULL
        CHECK (rental_hour BETWEEN 0 AND 23),
    observed_at         TIMESTAMPTZ NOT NULL,

    rented_bike_count   INTEGER     NOT NULL
        CHECK (rented_bike_count >= 0),

    temperature_c       NUMERIC(4, 1)
        CHECK (temperature_c BETWEEN -50 AND 50),
    humidity_pct        SMALLINT
        CHECK (humidity_pct BETWEEN 0 AND 100),
    wind_speed_ms       NUMERIC(4, 1)
        CHECK (wind_speed_ms >= 0),
    visibility_10m      SMALLINT
        CHECK (visibility_10m >= 0),
    dew_point_c         NUMERIC(4, 1)
        CHECK (dew_point_c BETWEEN -50 AND 50),
    solar_radiation_mj  NUMERIC(5, 2)
        CHECK (solar_radiation_mj >= 0),
    rainfall_mm         NUMERIC(5, 1)
        CHECK (rainfall_mm >= 0),
    snowfall_cm         NUMERIC(5, 1)
        CHECK (snowfall_cm >= 0),

    season              TEXT        NOT NULL
        CHECK (season IN ('Winter', 'Spring', 'Summer', 'Autumn')),
    is_holiday          BOOLEAN     NOT NULL,
    is_functioning_day  BOOLEAN     NOT NULL,

    CONSTRAINT uq_hw3_bike_rentals_date_hour UNIQUE (rental_date, rental_hour),
    CONSTRAINT ck_hw3_no_rentals_when_closed
        CHECK (is_functioning_day OR rented_bike_count = 0)
);
""")

In [8]:
run(r"""
WITH parsed AS (
    SELECT
        TO_DATE(NULLIF(TRIM(date_raw), ''), 'DD/MM/YYYY')   AS rental_date,
        hw3_to_num(hour_raw)::SMALLINT                       AS rental_hour,
        hw3_to_num(rented_bike_count_raw)::INTEGER           AS rented_bike_count,
        hw3_to_num(temperature_c_raw)::NUMERIC(4, 1)         AS temperature_c,
        hw3_to_num(humidity_pct_raw)::SMALLINT               AS humidity_pct,
        hw3_to_num(wind_speed_ms_raw)::NUMERIC(4, 1)         AS wind_speed_ms,
        hw3_to_num(visibility_10m_raw)::SMALLINT             AS visibility_10m,
        hw3_to_num(dew_point_c_raw)::NUMERIC(4, 1)           AS dew_point_c,
        hw3_to_num(solar_radiation_mj_raw)::NUMERIC(5, 2)    AS solar_radiation_mj,
        hw3_to_num(rainfall_mm_raw)::NUMERIC(5, 1)           AS rainfall_mm,
        hw3_to_num(snowfall_cm_raw)::NUMERIC(5, 1)           AS snowfall_cm,
        INITCAP(NULLIF(TRIM(seasons_raw), ''))               AS season,
        CASE LOWER(TRIM(holiday_raw))
            WHEN 'holiday'    THEN TRUE
            WHEN 'no holiday' THEN FALSE
        END                                                  AS is_holiday,
        CASE LOWER(TRIM(functioning_day_raw))
            WHEN 'yes' THEN TRUE
            WHEN 'no'  THEN FALSE
        END                                                  AS is_functioning_day
    FROM hw3_bike_staging
)
INSERT INTO hw3_bike_rentals (
    rental_date, rental_hour, observed_at, rented_bike_count,
    temperature_c, humidity_pct, wind_speed_ms, visibility_10m, dew_point_c,
    solar_radiation_mj, rainfall_mm, snowfall_cm,
    season, is_holiday, is_functioning_day
)
SELECT
    rental_date,
    rental_hour,
    (rental_date + rental_hour * INTERVAL '1 hour') AT TIME ZONE 'Asia/Seoul' AS observed_at,
    rented_bike_count,
    temperature_c, humidity_pct, wind_speed_ms, visibility_10m, dew_point_c,
    solar_radiation_mj, rainfall_mm, snowfall_cm,
    season, is_holiday, is_functioning_day
FROM parsed
WHERE rental_date IS NOT NULL
  AND rental_hour BETWEEN 0 AND 23
  AND rented_bike_count >= 0
  AND season IN ('Winter', 'Spring', 'Summer', 'Autumn')
  AND is_holiday IS NOT NULL
  AND is_functioning_day IS NOT NULL
ON CONFLICT (rental_date, rental_hour) DO NOTHING;
""")

In [9]:
q(r"""
SELECT
    rental_id, rental_date, rental_hour,
    observed_at AT TIME ZONE 'UTC'        AS observed_at_utc,
    observed_at AT TIME ZONE 'Asia/Seoul' AS observed_at_kst,
    rented_bike_count,
    temperature_c, humidity_pct, rainfall_mm, season, is_holiday, is_functioning_day
FROM hw3_bike_rentals
ORDER BY rental_id
LIMIT 5;
""")

   rental_id rental_date  rental_hour     observed_at_utc     observed_at_kst  rented_bike_count  temperature_c  humidity_pct  rainfall_mm  season  is_holiday  is_functioning_day
0          1  2017-12-01            0 2017-11-30 15:00:00 2017-12-01 00:00:00                254           -5.2            37          0.0  Winter       False                True
1          2  2017-12-01            1 2017-11-30 16:00:00 2017-12-01 01:00:00                204           -5.5            38          0.0  Winter       False                True
2          3  2017-12-01            2 2017-11-30 17:00:00 2017-12-01 02:00:00                173           -6.0            39          0.0  Winter       False                True
3          4  2017-12-01            3 2017-11-30 18:00:00 2017-12-01 03:00:00                107           -6.2            40          0.0  Winter       False                True
4          5  2017-12-01            4 2017-11-30 19:00:00 2017-12-01 04:00:00                 78           -6.0            36          0.0  Winter       False                True

**Висновок:** типізація працює: дата `01/12/2017` розпізнана як **1 грудня** 2017 (а не 12 січня), а 00:00 за Сеулом — це 15:00 UTC попереднього дня (`observed_at_utc`), тобто локалізація через `AT TIME ZONE 'Asia/Seoul'` дає правильний момент часу. Текстові `No Holiday` / `Yes` перетворені на `FALSE` / `TRUE`.

In [10]:
q(r"""
SELECT 'staging' AS layer, COUNT(*) AS n_rows
FROM hw3_bike_staging

UNION ALL

SELECT 'clean' AS layer, COUNT(*) AS n_rows
FROM hw3_bike_rentals;
""")

     layer  n_rows
0  staging    8760
1    clean    8760

**Висновок:** кількість рядків у staging і clean **однакова - 8 760**. Жоден рядок не відфільтровано: правило `WHERE` (дата у форматі `DD/MM/YYYY`, година 0–23, невід'ємний лічильник, відомий сезон, розпізнані прапорці) і `ON CONFLICT (rental_date, rental_hour) DO NOTHING` не спрацювали на жодному записі, а всі `CHECK`-обмеження пройдено без помилок.

In [11]:
q(r"""
WITH calendar AS (
    SELECT generate_series(MIN(rental_date), MAX(rental_date), INTERVAL '1 day')::DATE AS d
    FROM hw3_bike_rentals
),
per_day AS (
    SELECT rental_date, COUNT(*) AS hours_present
    FROM hw3_bike_rentals
    GROUP BY rental_date
)
SELECT
    MIN(c.d)                                                    AS first_day,
    MAX(c.d)                                                    AS last_day,
    COUNT(*)                                                    AS calendar_days,
    COUNT(*) FILTER (WHERE p.rental_date IS NULL)               AS missing_days,
    COUNT(*) FILTER (WHERE p.hours_present <> 24)               AS incomplete_days,
    COUNT(*) * 24                                               AS expected_hours
FROM calendar AS c
LEFT JOIN per_day AS p ON p.rental_date = c.d;
""")

    first_day    last_day  calendar_days  missing_days  incomplete_days  expected_hours
0  2017-12-01  2018-11-30            365             0                0            8760

**Висновок:** часовий ряд повний: 365 календарних днів з 01.12.2017 по 30.11.2018, жодного пропущеного дня і жодного дня з кількістю годин ≠ 24. Отже, 8 760 = 365 × 24, і для forecasting-задачі не потрібно відновлювати пропущені точки.

In [12]:
q(r"""
SELECT
    COUNT(*)                                                              AS total_rows,
    COUNT(DISTINCT (rental_date, rental_hour))                            AS distinct_business_keys,
    COUNT(*) - COUNT(DISTINCT (rental_date, rental_hour))                 AS duplicate_rows
FROM hw3_bike_rentals;
""")

   total_rows  distinct_business_keys  duplicate_rows
0        8760                    8760               0

In [13]:
q(r"""
SELECT
    COUNT(*)                                                              AS staging_rows,
    COUNT(DISTINCT (TRIM(date_raw), TRIM(hour_raw)))                      AS distinct_raw_keys,
    COUNT(*) - COUNT(DISTINCT (TRIM(date_raw), TRIM(hour_raw)))           AS duplicate_raw_keys,
    COUNT(*) - (SELECT COUNT(*) FROM (SELECT DISTINCT * FROM hw3_bike_staging) AS d)
                                                                          AS exact_duplicate_rows
FROM hw3_bike_staging;
""")

   staging_rows  distinct_raw_keys  duplicate_raw_keys  exact_duplicate_rows
0          8760               8760                   0                     0

**Висновок:** дублікатів немає ні за business key `(rental_date, rental_hour)` (і в clean, і в сирому staging), ні як повністю ідентичних рядків. Оскільки це справжній природний ключ погодинного ряду, перевірка є строгою, а не лише пошуком «потенційних» дублікатів; додатково його гарантує `UNIQUE`-обмеження в clean-таблиці.

In [14]:
q(r"""
SELECT
    COUNT(*)                                                                                      AS total_rows,
    ROUND(COUNT(*) FILTER (WHERE rented_bike_count  IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2)   AS pct_null_rented_bike_count,
    ROUND(COUNT(*) FILTER (WHERE temperature_c      IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2)   AS pct_null_temperature_c,
    ROUND(COUNT(*) FILTER (WHERE humidity_pct       IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2)   AS pct_null_humidity_pct,
    ROUND(COUNT(*) FILTER (WHERE wind_speed_ms      IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2)   AS pct_null_wind_speed_ms,
    ROUND(COUNT(*) FILTER (WHERE visibility_10m     IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2)   AS pct_null_visibility_10m,
    ROUND(COUNT(*) FILTER (WHERE dew_point_c        IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2)   AS pct_null_dew_point_c,
    ROUND(COUNT(*) FILTER (WHERE solar_radiation_mj IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2)   AS pct_null_solar_radiation_mj,
    ROUND(COUNT(*) FILTER (WHERE rainfall_mm        IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2)   AS pct_null_rainfall_mm,
    ROUND(COUNT(*) FILTER (WHERE snowfall_cm        IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2)   AS pct_null_snowfall_cm,
    ROUND(COUNT(*) FILTER (WHERE season             IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2)   AS pct_null_season,
    ROUND(COUNT(*) FILTER (WHERE is_holiday         IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2)   AS pct_null_is_holiday,
    ROUND(COUNT(*) FILTER (WHERE is_functioning_day IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2)   AS pct_null_is_functioning_day
FROM hw3_bike_rentals;
""")

,total_rows,pct_null_rented_bike_count,pct_null_temperature_c,pct_null_humidity_pct,pct_null_wind_speed_ms,pct_null_visibility_10m,pct_null_dew_point_c,pct_null_solar_radiation_mj,pct_null_rainfall_mm,pct_null_snowfall_cm,pct_null_season,pct_null_is_holiday,pct_null_is_functioning_day
0,8760,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
q(r"""
SELECT
    u.col,
    COUNT(*) FILTER (WHERE u.v IS NULL OR TRIM(u.v) = '')                                         AS empty_or_null,
    COUNT(*) FILTER (WHERE LOWER(TRIM(u.v)) IN ('?', 'na', 'n/a', 'nan', 'null', 'none', 'unknown', '-'))
                                                                                                  AS missing_markers,
    COUNT(*) FILTER (WHERE u.v <> TRIM(u.v))                                                      AS untrimmed,
    COUNT(*) FILTER (WHERE u.is_numeric AND TRIM(u.v) <> '' AND hw3_to_num(u.v) IS NULL)          AS non_numeric,
    COUNT(DISTINCT u.v)                                                                           AS n_distinct
FROM hw3_bike_staging AS s
CROSS JOIN LATERAL (
    VALUES
        ('date_raw',               s.date_raw,               FALSE),
        ('rented_bike_count_raw',  s.rented_bike_count_raw,  TRUE),
        ('hour_raw',               s.hour_raw,               TRUE),
        ('temperature_c_raw',      s.temperature_c_raw,      TRUE),
        ('humidity_pct_raw',       s.humidity_pct_raw,       TRUE),
        ('wind_speed_ms_raw',      s.wind_speed_ms_raw,      TRUE),
        ('visibility_10m_raw',     s.visibility_10m_raw,     TRUE),
        ('dew_point_c_raw',        s.dew_point_c_raw,        TRUE),
        ('solar_radiation_mj_raw', s.solar_radiation_mj_raw, TRUE),
        ('rainfall_mm_raw',        s.rainfall_mm_raw,        TRUE),
        ('snowfall_cm_raw',        s.snowfall_cm_raw,        TRUE),
        ('seasons_raw',            s.seasons_raw,            FALSE),
        ('holiday_raw',            s.holiday_raw,            FALSE),
        ('functioning_day_raw',    s.functioning_day_raw,    FALSE)
) AS u(col, v, is_numeric)
GROUP BY u.col
ORDER BY u.col;
""")

                       col  empty_or_null  missing_markers  untrimmed  non_numeric  n_distinct
0                 date_raw              0                0          0            0         365
1          dew_point_c_raw              0                0          0            0         556
2      functioning_day_raw              0                0          0            0           2
3              holiday_raw              0                0          0            0           2
4                 hour_raw              0                0          0            0          24
5         humidity_pct_raw              0                0          0            0          90
6          rainfall_mm_raw              0                0          0            0          61
7    rented_bike_count_raw              0                0          0            0        2166
8              seasons_raw              0                0          0            0           4
9          snowfall_cm_raw              0                0          0            0          51
10  solar_radiation_mj_raw              0                0          0            0         345
11       temperature_c_raw              0                0          0            0         546
12      visibility_10m_raw              0                0          0            0        1789
13       wind_speed_ms_raw              0                0          0            0          65

In [16]:
q(r"""
SELECT 'seasons_raw' AS col, seasons_raw AS raw_value, COUNT(*) AS n_rows
FROM hw3_bike_staging GROUP BY seasons_raw
UNION ALL
SELECT 'holiday_raw', holiday_raw, COUNT(*)
FROM hw3_bike_staging GROUP BY holiday_raw
UNION ALL
SELECT 'functioning_day_raw', functioning_day_raw, COUNT(*)
FROM hw3_bike_staging GROUP BY functioning_day_raw
UNION ALL
SELECT 'date_raw: not DD/MM/YYYY', NULL, COUNT(*)
FROM hw3_bike_staging WHERE date_raw !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'
ORDER BY col, n_rows DESC;
""")

                        col   raw_value  n_rows
0  date_raw: not DD/MM/YYYY         NaN       0
1       functioning_day_raw         Yes    8465
2       functioning_day_raw          No     295
3               holiday_raw  No Holiday    8328
4               holiday_raw     Holiday     432
5               seasons_raw      Spring    2208
6               seasons_raw      Summer    2208
7               seasons_raw      Autumn    2184
8               seasons_raw      Winter    2160

**Висновок:** null-rate усіх 13 змістовних колонок clean-таблиці - **0 %**, а в сирих даних немає порожніх рядків, маркерів `?`/`NA`/`unknown`, зайвих пробілів чи нечислових значень у числових колонках; усі дати мають формат `DD/MM/YYYY`. Категоріальні колонки мають лише очікувані значення (4 сезони, `Holiday`/`No Holiday`, `Yes`/`No`) без варіантів написання.

Це **не гарантує** повної якості: пропуски в цьому датасеті «замасковані» не як NULL, а як значення. Зокрема, 295 годин з `Functioning Day = No` мають `Rented Bike Count = 0` - це не реальний попит, а відсутність спостереження; `Visibility = 2000` (20 км) - верхня межа приладу (цензуровані значення, див. Reflection); а `Snowfall` поводиться як висота снігового покриву, а не як нові опади (див. 4.3). Ще одна дрібна проблема - заголовки джерела містять спецсимволи й одиниці виміру (`Temperature(°C)`), тому їх довелося перейменовувати.

In [17]:
q(r"""
SELECT
    season,
    COUNT(*) AS n_rows,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS pct_rows
FROM hw3_bike_rentals
GROUP BY season
ORDER BY n_rows DESC, season
LIMIT 10;
""")

   season  n_rows  pct_rows
0  Spring    2208     25.21
1  Summer    2208     25.21
2  Autumn    2184     24.93
3  Winter    2160     24.66

In [18]:
q(r"""
SELECT
    is_holiday,
    is_functioning_day,
    COUNT(*) AS n_rows,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS pct_rows
FROM hw3_bike_rentals
GROUP BY is_holiday, is_functioning_day
ORDER BY n_rows DESC
LIMIT 10;
""")

   is_holiday  is_functioning_day  n_rows  pct_rows
0       False                True    8057     91.97
1        True                True     408      4.66
2       False               False     271      3.09
3        True               False      24      0.27

**Висновок:** за `season` дисбалансу немає - кожен сезон займає ≈ 25 % (2 160–2 208 годин), бо сезон - це просто календарний поділ року на чверті. Натомість календарні прапорці суттєво незбалансовані: свята - лише **4,93 %** годин (432 години = 18 днів), а неробочі години сервісу - **3,37 %** (295 годин). Найрідкісніша комбінація «свято + сервіс не працює» - 24 години (0,27 %, один день 09.10.2018). Для ML це означає, що ефект свят оцінюється за малою кількістю днів, а неробочі години краще не змішувати з реальним попитом.

In [19]:
q(r"""
SELECT
    COUNT(rented_bike_count)                                                   AS n_non_null,
    MIN(rented_bike_count)                                                     AS min_value,
    MAX(rented_bike_count)                                                     AS max_value,
    ROUND(AVG(rented_bike_count)::NUMERIC, 2)                                  AS avg_value,
    ROUND(STDDEV_SAMP(rented_bike_count)::NUMERIC, 2)                          AS sd_value,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY rented_bike_count)            AS p25,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY rented_bike_count)            AS median,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY rented_bike_count)            AS p75
FROM hw3_bike_rentals;
""")

   n_non_null  min_value  max_value  avg_value  sd_value    p25  median      p75
0        8760          0       3556      704.6     645.0  191.0   504.5  1065.25

**Висновок:** лічильник оренд змінюється від 0 до 3 556 за годину, середнє - **704,6**, стандартне відхилення - **645**, тобто варіація майже дорівнює середньому. Медіана (504,5) помітно нижча за середнє, а p75 = 1 065: розподіл **правосторонньо асиметричний** (багато нічних і зимових годин з малим попитом, мало дуже пікових). Для регресії варто розглянути лог-трансформацію target або метрику, стійку до масштабу (RMSLE).

In [20]:
q(r"""
SELECT
    CASE
        WHEN NOT is_functioning_day AND rented_bike_count > 0  THEN '1. rentals on non-functioning hour'
        WHEN is_functioning_day     AND rented_bike_count = 0  THEN '2. zero rentals on functioning hour'
        WHEN dew_point_c > temperature_c                       THEN '3. dew point above temperature'
        WHEN (snowfall_cm > 0 AND temperature_c > 5)
          OR (rainfall_mm > 0 AND temperature_c <= -10)        THEN '4. implausible precipitation'
    END                         AS anomaly_type,
    COUNT(*)                    AS n_rows,
    MIN(rental_date)            AS first_date,
    MAX(rental_date)            AS last_date
FROM hw3_bike_rentals
WHERE (NOT is_functioning_day AND rented_bike_count > 0)
   OR (is_functioning_day AND rented_bike_count = 0)
   OR dew_point_c > temperature_c
   OR (snowfall_cm > 0 AND temperature_c > 5)
   OR (rainfall_mm > 0 AND temperature_c <= -10)
GROUP BY 1
ORDER BY 1;
""")

                   anomaly_type  n_rows  first_date   last_date
0  4. implausible precipitation      14  2017-12-10  2018-11-25

In [21]:
q(r"""
SELECT
    rental_date,
    rental_hour,
    temperature_c,
    dew_point_c,
    rainfall_mm,
    snowfall_cm,
    rented_bike_count,
    is_functioning_day
FROM hw3_bike_rentals
WHERE (NOT is_functioning_day AND rented_bike_count > 0)
   OR (is_functioning_day AND rented_bike_count = 0)
   OR dew_point_c > temperature_c
   OR (snowfall_cm > 0 AND temperature_c > 5)
   OR (rainfall_mm > 0 AND temperature_c <= -10)
ORDER BY rental_date, rental_hour
LIMIT 20;
""")

   rental_date  rental_hour  temperature_c  dew_point_c  rainfall_mm  snowfall_cm  rented_bike_count  is_functioning_day
0   2017-12-10           15            6.7          0.1          0.0          1.0                180                True
1   2017-12-10           16            5.4          0.5          0.0          0.5                214                True
2   2018-02-23           12            5.3          0.2          0.0          1.7                283                True
3   2018-02-23           13            6.7          0.3          0.0          0.6                304                True
4   2018-11-25           11            6.0          0.1          0.0          2.3                522                True
5   2018-11-25           12            6.9         -0.5          0.0          2.2                700                True
6   2018-11-25           13            8.8         -0.2          0.0          1.8                675                True
7   2018-11-25           14            9.2         -0.1          0.0          1.3                777                True
8   2018-11-25           15            9.5          0.6          0.0          1.1                846                True
9   2018-11-25           16            9.5          1.1          0.0          0.8                872                True
10  2018-11-25           17            9.0          1.4          0.0          0.4                813                True
11  2018-11-25           18            7.3          2.5          0.0          0.4                663                True
12  2018-11-25           19            6.3          1.8          0.0          0.4                616                True
13  2018-11-25           20            5.5          1.7          0.0          0.4                570                True

In [22]:
q(r"""
WITH stats AS (
    SELECT
        AVG(rented_bike_count)          AS mean_value,
        STDDEV_SAMP(rented_bike_count)  AS sd_value
    FROM hw3_bike_rentals
    WHERE is_functioning_day
)
SELECT
    t.rental_date,
    t.rental_hour,
    t.season,
    t.temperature_c,
    t.rainfall_mm,
    t.rented_bike_count,
    ROUND(((t.rented_bike_count - s.mean_value) / NULLIF(s.sd_value, 0))::NUMERIC, 2) AS z_score
FROM hw3_bike_rentals AS t
CROSS JOIN stats AS s
WHERE t.is_functioning_day
  AND s.sd_value > 0
  AND ABS(t.rented_bike_count - s.mean_value) > 3 * s.sd_value
ORDER BY ABS(t.rented_bike_count - s.mean_value) DESC
LIMIT 20;
""")

   rental_date  rental_hour  season  temperature_c  rainfall_mm  rented_bike_count  z_score
0   2018-06-19           18  Summer           24.1          0.0               3556     4.40
1   2018-06-21           18  Summer           27.8          0.0               3418     4.19
2   2018-06-12           18  Summer           24.9          0.0               3404     4.16
3   2018-06-20           18  Summer           27.0          0.0               3384     4.13
4   2018-06-04           18  Summer           24.4          0.0               3380     4.13
5   2018-06-22           18  Summer           29.3          0.0               3365     4.10
6   2018-06-08           18  Summer           26.2          0.0               3309     4.02
7   2018-09-10           18  Autumn           25.9          0.0               3298     4.00
8   2018-09-17           18  Autumn           25.3          0.0               3277     3.97
9   2018-09-12           18  Autumn           27.0          0.0               3256     3.93
10  2018-05-30           18  Spring           23.6          0.0               3251     3.93
11  2018-05-28           18  Spring           26.0          0.0               3245     3.92
12  2018-06-25           18  Summer           30.7          0.0               3238     3.91
13  2018-06-05           18  Summer           27.1          0.0               3227     3.89
14  2018-09-11           18  Autumn           24.7          0.0               3222     3.88
15  2018-06-07           18  Summer           25.6          0.0               3221     3.88
16  2018-07-06           18  Summer           25.9          0.0               3196     3.84
17  2018-06-27           18  Summer           25.0          0.0               3172     3.80
18  2018-09-04           18  Autumn           26.8          0.0               3166     3.79
19  2018-09-05           18  Autumn           27.0          0.0               3160     3.78

In [23]:
q(r"""
WITH stats AS (
    SELECT AVG(rented_bike_count) AS m, STDDEV_SAMP(rented_bike_count) AS sd
    FROM hw3_bike_rentals
    WHERE is_functioning_day
)
SELECT
    COUNT(*)                                          AS n_outliers_3sigma,
    MIN(t.rental_hour)                                AS min_hour,
    MAX(t.rental_hour)                                AS max_hour,
    STRING_AGG(DISTINCT t.season, ', ')               AS seasons
FROM hw3_bike_rentals AS t
CROSS JOIN stats AS s
WHERE t.is_functioning_day
  AND ABS(t.rented_bike_count - s.m) > 3 * s.sd;
""")

   n_outliers_3sigma  min_hour  max_hour                 seasons
0                 63        17        19  Autumn, Spring, Summer

**Висновок доменної перевірки:**
- **Правила 1-2 - 0 рядків.** Оренди в неробочий час неможливі (до того ж це гарантує `CHECK` у DDL), і, що важливіше, немає жодної робочої години з нулем оренд. Тобто `rented_bike_count = 0` ⇔ `is_functioning_day = FALSE` для всіх 295 годин — нулі в target є технічними, а не поведінковими.
- **Правило 3 - 0 рядків:** точка роси ніде не перевищує температуру, метеодані фізично узгоджені.
- **Правило 4 - 14 рядків**, усі з типу «сніг при > 5 °C» (10.12.2017, 23.02.2018, 25.11.2018). На 25.11.2018 `snowfall_cm` плавно спадає з 2,3 до 0,4 см протягом 10 годин при +6…+9,5 °C, а дощу немає. Це вказує, що колонка, ймовірно, фіксує **висоту снігового покриву** (сніг, що тане), а не нові опади. **Дія:** не видаляти, додати прапорець `snow_on_ground_flag` і **передати на перевірку джерела** семантику колонки; у feature engineering трактувати її як «сніг на землі».

**Висновок перевірки 3σ:** серед робочих годин 63 значення перевищують середнє більш ніж на 3σ (z до 4,40, максимум 3 556 оренд 19.06.2018). Усі вони припадають на **17-19 годину** сухих теплих (≈ 24–30 °C) днів весни, літа й осені - це реальний вечірній пік поїздок з роботи, а не помилка. **Дія:** залишити як валідний рідкісний випадок; правило 3σ тут некоректне, бо розподіл асиметричний і сильно залежить від години та сезону.

In [24]:
q(r"""
SELECT
    rental_hour,
    COUNT(*)                                   AS n_hours,
    ROUND(AVG(rented_bike_count), 1)           AS avg_rentals,
    SUM(rented_bike_count)                     AS total_rentals
FROM hw3_bike_rentals
WHERE is_functioning_day
GROUP BY rental_hour
ORDER BY avg_rentals DESC
LIMIT 5;
""")

   rental_hour  n_hours  avg_rentals  total_rentals
0           18      353       1554.0         548568
1           19      353       1235.8         436229
2           17      353       1177.2         415556
3           20      353       1105.3         390172
4           21      353       1066.5         376479

**Interpretation:** найбільший середній попит - о **18:00 (1 554 оренди/год)**, далі 19:00 (1 236) і 17:00 (1 177); 20:00 і 21:00 теж перевищують 1 000. Вечірній пік після роботи - найсильніший патерн у даних, і він приблизно на третину вищий за наступну годину. Отже, `rental_hour` - ключова ознака, а планування ребалансування велосипедів варто орієнтувати на 17-21 годину.

In [25]:
q(r"""
SELECT
    season,
    COUNT(*)                                                   AS n_hours,
    SUM(rented_bike_count)                                     AS total_rentals,
    ROUND(AVG(rented_bike_count), 1)                           AS avg_rentals_per_hour,
    ROUND(SUM(rented_bike_count) * 100.0
          / SUM(SUM(rented_bike_count)) OVER (), 2)            AS pct_of_year_rentals,
    ROUND(AVG(temperature_c), 1)                               AS avg_temperature_c
FROM hw3_bike_rentals
WHERE is_functioning_day
GROUP BY season
ORDER BY avg_rentals_per_hour DESC;
""")

   season  n_hours  total_rentals  avg_rentals_per_hour  pct_of_year_rentals  avg_temperature_c
0  Summer     2208        2283234                1034.1                36.99               26.6
1  Autumn     1937        1790002                 924.1                29.00               13.8
2  Spring     2160        1611909                 746.3                26.12               13.0
3  Winter     2160         487169                 225.5                 7.89               -2.5

**Interpretation:** найвищий попит улітку - **1 034 оренди/год**, що дає 37 % річних оренд; восени - 924, навесні - 746, а взимку лише **225,5** (7,9 % року), тобто зимою попит у ~4,6 раза нижчий, ніж улітку. Цікаво, що восени попит вищий, ніж навесні, при майже однаковій середній температурі (13,8 vs 13,0 °C) - сезон містить інформацію понад температуру. Восени також менше робочих годин (1 937 з 2 184) через неробочі дні сервісу.

In [26]:
q(r"""
SELECT
    is_holiday,
    CASE
        WHEN rental_hour BETWEEN 7 AND 9 OR rental_hour BETWEEN 17 AND 19 THEN 'commute peak (7-9, 17-19)'
        ELSE 'daytime off-peak (10-16)'
    END                                        AS period,
    COUNT(*)                                   AS n_hours,
    ROUND(AVG(rented_bike_count), 1)           AS avg_rentals
FROM hw3_bike_rentals
WHERE is_functioning_day
  AND rental_hour BETWEEN 7 AND 19
GROUP BY is_holiday, period
ORDER BY period, is_holiday;
""")

   is_holiday                     period  n_hours  avg_rentals
0       False  commute peak (7-9, 17-19)     2016       1075.8
1        True  commute peak (7-9, 17-19)      102        581.5
2       False   daytime off-peak (10-16)     2352        753.7
3        True   daytime off-peak (10-16)      119        685.5

**Interpretation:** у звичайні дні в години пік (7-9, 17-19) в середньому **1 076** оренд/год, а у свята - лише **582**, тобто майже вдвічі менше. Удень поза піком різниця мала: 754 vs 686. Отже, свята «з'їдають» саме поїздки на роботу, а дозвільний попит майже не змінюється - модель повинна враховувати взаємодію `is_holiday × rental_hour`, а не лише окремий прапорець (зважаючи на малу вибірку: 102 і 119 святкових годин).

In [27]:
q(r"""
SELECT DISTINCT
    rental_date,
    season,
    is_holiday
FROM hw3_bike_rentals
WHERE NOT is_functioning_day
ORDER BY rental_date;
""")

   rental_date  season  is_holiday
0   2018-04-11  Spring       False
1   2018-05-10  Spring       False
2   2018-09-18  Autumn       False
3   2018-09-19  Autumn       False
4   2018-09-28  Autumn       False
5   2018-09-30  Autumn       False
6   2018-10-02  Autumn       False
7   2018-10-04  Autumn       False
8   2018-10-06  Autumn       False
9   2018-10-09  Autumn        True
10  2018-11-03  Autumn       False
11  2018-11-06  Autumn       False
12  2018-11-09  Autumn       False

**Interpretation:** сервіс не працював у **13** календарних днях - усі у 2018 році з квітня по листопад: 11.04, 10.05, 18–19.09, 28.09, 30.09, 02.10, 04.10, 06.10, 09.10 (єдиний свят серед них), 03.11, 06.11, 09.11. Взимку 2017/18 неробочих днів немає, а восени вони зосереджені особливо щільно, що схоже на техобслуговування або збої обліку. Для ML ці дні варто виключити з training data або моделювати окремо, бо їхні нулі не відображають попит.

In [28]:
q(r"""
SELECT
    CASE
        WHEN (rainfall_mm > 0 OR snowfall_cm > 0) THEN 'precipitation'
        ELSE 'dry'
    END                                        AS weather,
    COUNT(*)                                   AS n_hours,
    ROUND(AVG(rented_bike_count), 1)           AS avg_rentals,
    MIN(rented_bike_count)                     AS min_rentals,
    MAX(rented_bike_count)                     AS max_rentals
FROM hw3_bike_rentals
WHERE rental_hour IN (17, 18, 19)
  AND is_functioning_day
  AND NOT is_holiday
  AND EXTRACT(ISODOW FROM rental_date) BETWEEN 1 AND 5
  AND (season = 'Summer' OR season = 'Spring' OR season = 'Autumn')
GROUP BY weather
ORDER BY avg_rentals DESC;
""")

         weather  n_hours  avg_rentals  min_rentals  max_rentals
0            dry      500       1870.1           19         3556
1  precipitation       37        351.1           23         2598

**Interpretation:** у робочі (пн–пт, не свята) вечори 17-19 год весни, літа й осені за сухої погоди в середньому **1 870** оренд/год, а за опадів - лише **351**, тобто падіння приблизно в **5,3 раза**. Мінімуми однакові (19 vs 23), але максимум за опадів значно нижчий. Навіть у найпіковіший час опади - домінуючий стримуючий фактор, хоча годин з опадами лише 37 із 537, тому оцінку слід сприймати з обережністю.

In [29]:
q(r"""
SELECT DISTINCT
    s.holiday_raw,
    r.is_holiday
FROM hw3_bike_staging AS s
JOIN hw3_bike_rentals AS r
  ON r.rental_date = TO_DATE(s.date_raw, 'DD/MM/YYYY')
 AND r.rental_hour = s.hour_raw::SMALLINT
WHERE s.holiday_raw ILIKE '%holiday%'
ORDER BY s.holiday_raw;
""")

  holiday_raw  is_holiday
0     Holiday        True
1  No Holiday       False

**Interpretation:** шаблон `ILIKE '%holiday%'` знаходить **обидві** сирі мітки - `Holiday` і `No Holiday`, і вони коректно мапляться на `TRUE` та `FALSE` відповідно (по одному значенню BOOLEAN на мітку, без конфліктів). Цей результат показує, чому нормалізацію не можна робити через «містить слово holiday»: такий наївний підхід позначив би святами 100 % годин. Тому в очищенні використано точне порівняння `CASE LOWER(TRIM(...))`.

In [30]:
q(r"""
WITH ordered AS (
    SELECT
        observed_at,
        rental_date,
        rental_hour,
        is_functioning_day,
        LAG(is_functioning_day) OVER (ORDER BY observed_at) AS prev_is_functioning_day
    FROM hw3_bike_rentals
)
SELECT
    rental_date,
    rental_hour,
    prev_is_functioning_day,
    is_functioning_day
FROM ordered
WHERE prev_is_functioning_day IS NOT NULL
  AND is_functioning_day IS DISTINCT FROM prev_is_functioning_day
ORDER BY observed_at;
""")

   rental_date  rental_hour  prev_is_functioning_day  is_functioning_day
0   2018-04-11            0                     True               False
1   2018-04-12            0                    False                True
2   2018-05-10            0                     True               False
3   2018-05-11            0                    False                True
4   2018-09-18            0                     True               False
5   2018-09-20            0                    False                True
6   2018-09-28            0                     True               False
7   2018-09-29            0                    False                True
8   2018-09-30            0                     True               False
9   2018-10-01            0                    False                True
10  2018-10-02            0                     True               False
11  2018-10-03            0                    False                True
12  2018-10-04            0                     True               False
13  2018-10-05            0                    False                True
14  2018-10-06            0                     True               False
15  2018-10-06            7                    False                True
16  2018-10-09            0                     True               False
17  2018-10-10            0                    False                True
18  2018-11-03            0                     True               False
19  2018-11-04            0                    False                True
20  2018-11-06            0                     True               False
21  2018-11-07            0                    False                True
22  2018-11-09            0                     True               False
23  2018-11-10            0                    False                True

**Interpretation:** статус роботи змінюється **24 рази** - 12 пар «вимкнено -> увімкнено». 23 із 24 переходів відбуваються рівно о 00:00, тобто неробочий період - це цілий календарний день. Єдиний виняток - 06.10.2018: сервіс не працював з 00:00 до 06:59 і відновився о 07:00. `IS DISTINCT FROM` у порівнянні з `LAG` - NULL-безпечний варіант (а перший рядок, де LAG = NULL, виключено явно). Отже, для фільтрації неробочих періодів недостатньо прапорця на рівні дня - потрібен погодинний.

In [31]:
q(r"""
SELECT
    season,
    ROUND(COUNT(*) FILTER (WHERE rainfall_mm > 0 OR snowfall_cm > 0) * 100.0
          / NULLIF(COUNT(*), 0), 2)                                         AS pct_hours_with_precip,
    ROUND(AVG(rented_bike_count) FILTER (WHERE rainfall_mm = 0 AND snowfall_cm = 0), 1)
                                                                            AS avg_dry,
    ROUND(COALESCE(AVG(rented_bike_count) FILTER (WHERE rainfall_mm > 0 OR snowfall_cm > 0), 0), 1)
                                                                            AS avg_precip,
    ROUND(
        AVG(rented_bike_count) FILTER (WHERE rainfall_mm = 0 AND snowfall_cm = 0)
        / NULLIF(AVG(rented_bike_count) FILTER (WHERE rainfall_mm > 0 OR snowfall_cm > 0), 0),
        2
    )                                                                       AS dry_to_precip_ratio
FROM hw3_bike_rentals
WHERE is_functioning_day
GROUP BY season
ORDER BY dry_to_precip_ratio DESC;
""")

   season  pct_hours_with_precip  avg_dry  avg_precip  dry_to_precip_ratio
0  Spring                   8.84    809.7        91.8                 8.82
1  Summer                   8.92   1110.1       257.9                 4.30
2  Autumn                   7.02    974.7       253.9                 3.84
3  Winter                  18.84    242.1       154.2                 1.57

**Interpretation:** опади найчастіші взимку (18,8 % годин, переважно через сніг на землі), у решту сезонів - 7-9 %. Найсильніше опади пригнічують попит навесні: суха година - **810** оренд, година з опадами - **92**, тобто в **8,8 раза** менше; влітку і восени - у 4,3 і 3,8 раза, а взимку лише в 1,57 раза. Слабкий зимовий ефект узгоджується з гіпотезою, що `snowfall_cm` часто описує сніговий покрив, а не активні опади, і з низьким базовим зимовим попитом. `NULLIF` захищає від ділення на нуль, а `COALESCE` - від `NULL`, якщо в сезоні немає годин з опадами.

In [32]:
q(r"""
SELECT
    COUNT(*)                                                     AS total_hours,
    COUNT(*) FILTER (
        WHERE temperature_c IS NULL OR humidity_pct IS NULL OR wind_speed_ms IS NULL
           OR visibility_10m IS NULL OR dew_point_c IS NULL OR solar_radiation_mj IS NULL
           OR rainfall_mm IS NULL OR snowfall_cm IS NULL
    )                                                            AS hours_with_any_null_weather,
    COUNT(*) FILTER (
        WHERE temperature_c IS NOT NULL AND humidity_pct IS NOT NULL AND wind_speed_ms IS NOT NULL
          AND visibility_10m IS NOT NULL AND dew_point_c IS NOT NULL AND solar_radiation_mj IS NOT NULL
          AND rainfall_mm IS NOT NULL AND snowfall_cm IS NOT NULL
    )                                                            AS hours_with_full_weather
FROM hw3_bike_rentals;
""")

   total_hours  hours_with_any_null_weather  hours_with_full_weather
0         8760                            0                     8760

**Interpretation:** у всіх **8 760** годинах заповнені всі вісім метеополів, годин з будь-яким `NULL` - 0. Це підтверджує аудит 3.3: `hw3_to_num` не перетворив жодне значення на `NULL`. Відсутність `NULL` не означає відсутність проблем - обмеження приладів (`visibility_10m = 2000`) та семантика снігу залишаються ризиками.

In [33]:
q(r"""
SELECT
    CASE
        WHEN temperature_c < 0                  THEN '1) < 0 °C'
        WHEN temperature_c BETWEEN 0 AND 9.9    THEN '2) 0-10 °C'
        WHEN temperature_c BETWEEN 10 AND 19.9  THEN '3) 10-20 °C'
        WHEN temperature_c BETWEEN 20 AND 29.9  THEN '4) 20-30 °C'
        ELSE                                         '5) >= 30 °C'
    END                                        AS temp_band,
    COUNT(*)                                   AS n_hours,
    ROUND(AVG(rented_bike_count), 1)           AS avg_rentals,
    ROUND(AVG(humidity_pct), 1)                AS avg_humidity_pct
FROM hw3_bike_rentals
WHERE is_functioning_day
GROUP BY temp_band
ORDER BY temp_band;
""")

     temp_band  n_hours  avg_rentals  avg_humidity_pct
0    1) < 0 °C     1433        198.0              47.1
1   2) 0-10 °C     2118        426.3              59.4
2  3) 10-20 °C     2050        837.2              60.5
3  4) 20-30 °C     2340       1148.1              63.5
4  5) >= 30 °C      524       1112.2              50.3

**Interpretation:** попит монотонно зростає з температурою: від **198** оренд/год при < 0 °C до **1 148** при 20–30 °C (у ~5,8 раза більше). У найспекотніших годинах (≥ 30 °C) попит трохи знижується до **1 112**, тобто залежність нелінійна з насиченням. Для лінійної моделі доцільно додати бінування або нелінійні члени температури.

In [34]:
q(r"""
SELECT
    rental_date,
    TO_CHAR(rental_date, 'Dy')                 AS weekday,
    season,
    SUM(rented_bike_count)                     AS daily_rentals,
    ROUND(AVG(temperature_c), 1)               AS avg_temperature_c,
    SUM(rainfall_mm)                           AS rainfall_mm_day
FROM hw3_bike_rentals
GROUP BY rental_date, season
ORDER BY daily_rentals DESC
LIMIT 10;
""")

  rental_date weekday  season  daily_rentals  avg_temperature_c  rainfall_mm_day
0  2018-06-13     Wed  Summer          36149               22.0              0.0
1  2018-06-19     Tue  Summer          35349               22.6              0.0
2  2018-06-08     Fri  Summer          35103               21.7              0.0
3  2018-06-20     Wed  Summer          34639               22.7              0.0
4  2018-06-21     Thu  Summer          34621               23.6              0.0
5  2018-06-12     Tue  Summer          34544               21.2              1.0
6  2018-06-16     Sat  Summer          34360               22.3              0.0
7  2018-06-22     Fri  Summer          34079               24.7              0.0
8  2018-07-06     Fri  Summer          33676               24.1              0.0
9  2018-06-15     Fri  Summer          33492               21.9             16.5

**Interpretation:** усі 10 найзавантаженіших днів - **літні**, 9 з 10 - у червні 2018 (13.06 - рекорд 36 149 оренд), з середньою температурою ≈ 21–25 °C, і 9 з 10 - будні (лише одна субота). Більшість із них сухі, але 15.06 потрапив у топ попри 16,5 мм дощу - ймовірно, дощ ішов у години з невисоким попитом. Помірне тепло й будній день - найсприятливіше поєднання для попиту.

**Якість даних.** Формально датасет «ідеальний»: немає `NULL`, маркерів `?`/`unknown`, дублікатів чи некоректних діапазонів, а часова сітка повна (365 × 24). Справжні проблеми приховані в значеннях: 295 нулів у target є технічними (сервіс не працював), `visibility_10m` обрізана на 2000 (2 245 годин = цензуровані значення), `snowfall_cm` поводиться як висота снігового покриву, а заголовки в cp1252 мають спецсимволи. Дату у форматі `DD/MM/YYYY` легко помилково прочитати як MM/DD.

**Features.** Використав би `rental_hour`, день тижня та місяць (похідні від `rental_date`), `season`, `is_holiday`, температуру, вологість, вітер, видимість, опади, сонячну радіацію. `dew_point_c` майже дублює температуру (кореляція 0,91) - залишив би лише одну з них. Не використав би `rental_id` і саму дату як число (ризик запам'ятати тренд).

**Leakage.** `is_functioning_day` повністю визначає нуль у target, і для майбутнього заздалегідь не відомий - такі години краще виключити з навчання. Фактична погода в годину прогнозу відома лише постфактум: у продакшні її треба замінити прогнозом погоди. Сусідні години одного дня не можна розкидати випадково між train і test - потрібен часовий split.

**Pipeline.** Попросив би data engineer віддавати UTF-8 з `snake_case`-заголовками, дати в ISO 8601 з часовим поясом, явний статус «немає даних» замість нуля, документувати одиниці та семантику снігу, а також додати ідентифікатор станції.

**ML-задача:** погодинна **regression / forecasting** кількості оренд (часовий ряд з екзогенними погодними ознаками).